
#      Eula Craft     #
# ################### #
#  Created by Pikod   #
#  Sub my channel :)  #
#  VERSION 0.1        # 
# ################### #
# Youtube.com/c/pikod #

# Plugin is enabled?
enabled: true

# kick > Kick the player
# none > Close menu and don't do anything (Menu is open after player try to move)
on-reject: kick

kick-message: '&cPlease accept agreement!' # Do not use &l

# none > Disable
accepted-message: '&aThanks for accept agreement!'

#Title of menu:
title: '&8Server Agreement'

# Slots start at zero

#Eula:
eula:
    text: '&aAgreement'
    lore:
    - '&2I will not use hack.'
    - '&2I will not swear.'
    - '&2I will follow the rules.'
    item: BOOK
    enchanted: false
    slot: 13
    
#Accept button:
accept: 
    text: '&aAccept'
    item: EMERALD
    enchanted: false
    slot: 11

#Reject button:
reject: 
    text: '&cReject'
    item: REDSTONE
    enchanted: false
    slot: 15